epics:
  project: "Shazam Road Map"
  status:
    - "In Progress"
    - "Closed"
    - "Open"
    - "Resolved"

  fields:
    shipping:
      label: Shipped
      states: Closed
      resolution:
        - Done
        - Completed
        - Fixed
      sorting: time
      limit: "-7 days"
      display:
        since: false
        states_color: limegreen

    release:
      label: Awaiting Release
      states: Resolved
      sorting: time
      display:
        since: true
        states_color: time
        time_color: time
        time:
          "-45 days": red
          "-30 days": yellow
          normal: darkgreen

    progress:
      label: In flight
      states: In Progress
      sorting: time
      display:
        since: true
        states_color: time
        time_color: time
        time:
          "-45 days": red
          "-30 days": yellow
          normal: white

    delayed:
      label: Delayed
      states: Open
      sorting: time
      display:
        since: false
        states_color: yellow

    cancelled:
      label: Cancelled
      states: Closed
      sorting: time
      limit: "-7 days"
      display:
        since: false
        states_color: red

    open:
      label: ""
      sorting: team-group
      display:
        since: false
        states_color: white

    unscheduled:
      label: ""
      states: Open
      sorting: time
      display:
        since: false
        states_color: blue

incidents:
  project: "Incident Management"
  priorities:
    - Critical
    - Major
    - Minor

smell_levels:
  1: 3600 # 1 hour
  2: 86400 # 1 day

teams:
  iOS Team:
    key: SIO
    id: 10150
  Android Team:
    key: SOA
    id: 10201
  AMP:
    key: AMP
    id: 10054
  AMP News:
    key: NWS
    id: 10011
  Data Team:
    key: DEN
    id: 10241
  Web Team:
    key: WPS
    id: 10032
  Server Team:
    key: AMP
    id: 10054
  Ingestion Team:
    key: DMT
    id: 10063
  Experiences Team:
    key: TVT
    id: 10051
  Recognition Infrastructure:
    key: RIN
    id: 10951
  Recognition Algorithm:
    key: RAD
    id: 11453
  Shazam Connect:
    key: SSP
    id: 10242
  Infrastructure Ops:
    key: OPS
    id: 10070
  DBA Team:
    key: OPS
    id: 10070
  SE - YellowTeam:
    key: SE
    id: 11352
  Service Engineering:
    key: SE
    id: 11352
  Experiences Services:
    key: TVT
    id: 10051
  Infra Tools:
    key: ITL
    id: 10211
  IT Ops:
    key: OPS
    id: 10070
