epics:
  project: "Shazam Road Map"
  status:
    - "In Progress"
    - "Closed"

incidents:
  project: "Incident Management"
  priorities:
    - Critical
    - Major
    - Minor

smell_levels:
  1: 3600 # 1 hour
  2: 86400 # 1 day
