root_point: "/jira-flightboard"

log:
  file: /var/log/jira-flightboard.log

jira_api:
  token: a8fgsd8f7ga8sawhfuwbg8berg8abegr87bae
  endpoint: https://jira.yourdomain.net/rest/api/2/

epics:
  project: "Epics Project Name"
  status:
    - "In Progress"
    - "Closed"
    - "Open"
    - "Resolved"

  fields:
    shipping:
      label: Shipped
      states: Closed
      resolution:
        - Done
        - Completed
        - Fixed
      sorting: time
      limit: "-7 days"
      display:
        since: false
        states_color: limegreen

    release:
      label: Awaiting Release
      states: Resolved
      sorting: time
      display:
        since: true
        states_color: time
        time_color: time
        time:
          "-45 days": red
          "-30 days": yellow
          normal: darkgreen

    progress:
      label: In flight
      states: In Progress
      sorting: time
      display:
        since: true
        states_color: time
        time_color: time
        time:
          "-45 days": red
          "-30 days": yellow
          normal: white

    delayed:
      label: Delayed
      states: Open
      sorting: time
      display:
        since: false
        states_color: yellow

    cancelled:
      label: Cancelled
      states: Closed
      sorting: time
      limit: "-7 days"
      display:
        since: false
        states_color: red

    open:
      label: ""
      sorting: team-group
      display:
        since: false
        states_color: white

    unscheduled:
      label: ""
      states: Open
      sorting: time
      display:
        since: false
        states_color: blue

smell_levels:
  1: 3600 # 1 hour
  2: 86400 # 1 day

teams:
  iOS Team:
    key: IOS
    id: 12345
  Android Team:
    key: AND
    id: 12346
  Web Team:
    key: WEB
    id: 12347
